---
# This file installs zookeeper (SUPPORT FROM: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-an-apache-zookeeper-cluster-on-ubuntu-18-04)


- name: Install EPEL 
  yum: 
    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Run Yum Update
  yum:
    name: '*'
    state: latest

- name: Install Required Brooklin packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - java-1.8.0-openjdk
    - epel-release
    - jq
    - python2-pip.noarch

- name: Ensure group zk exists
  group:
    name: zk
    state: present

- name: Setup Zookeeper user
  user:
    name: zk
    comment: Zookeeper user
    groups: zk,wheel

- name: Create Kafka Install Dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: zk
    group: zk
  with_items:
    - /brooklin
    - /brooklin/kafka

- name: Check if ZooKeeper has already been downloaded and unpacked
  stat:
    path: /brooklin/kafka/{{ KAFKA_TGZ }}
  register: dir

- name: Download Kafka
  get_url:
    url: "https://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/{{ KAFKA_TGZ }}"
    dest: /brooklin/kafka
  when: not dir.stat.exists

- name: Unpack Kafka
  unarchive:
    remote_src: yes
    src: /brooklin/kafka/{{ KAFKA_TGZ }}
    dest: /brooklin/kafka/
    owner: zk
    group: zk
  when: not dir.stat.exists

- name: Update Zookeeper Config
  copy:
    src: zookeeper.properties
    dest: "/brooklin/kafka/{{ KAFKA_FILENAME }}/config/zookeeper.properties"
    owner: zk
    group: zk

# - name: Create Systemd Service
#   template: 
#     src: zk.service.j2
#     dest: /etc/systemd/system/zk.service
#     owner: bin
#     group: wheel
#     mode: '0644'

- name: Open Zookeeper Port
  firewalld:
    port: 2181/tcp
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

- name: Start Zookeeper Service
  chdir: /brooklin/kafka/{{ KAFKA_FILENAME }}
  shell: bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &
  become_user: zk

