---
# This file installs zookeeper (example: https://blog.redbranch.net/2018/04/19/zookeeper-install-on-centos-7/)


- name: Install EPEL 
  yum: 
    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Run Yum Update
  yum:
    name: '*'
    state: latest

- name: Install Required Zookeeper packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - java-1.8.0-openjdk

- name: Ensure group zk exists
  group:
    name: zk
    state: present

- name: Setup Zookeeper user
  user:
    name: zk
    comment: Zookeeper user
    groups: zk,wheel

- name: Check if ZooKeeper has already been downloaded and unpacked
  stat:
    path: /zookeper/{{ ZOOKEEPER_TARGZ }}
  register: zk_dir

- name: Download Zookeeper
  get_url:
    url: "http://apache.mirrors.pair.com/zookeeper/zookeeper-{{ ZOOKEEPER_VERSION }}/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz"
    dest: /opt
  when: not zk_dir.stat.exists

- name: Unpack Zookeeper
  unarchive:
    remote_src: yes
    src: /opt/{{ ZOOKEEPER_TARGZ }}
    dest: /opt
    owner: zk
    group: zk
  when: not zk_dir.stat.exists

- name: Symlink Zookeeper
  file:
    src: "/opt/zookeeper-{{ ZOOKEEPER_VERSION }}"
    dest: "/opt/zookeeper"
    state: link
    owner: zk
    group: zk

- name: Zookeeper Data zk_dir
  file: 
    path: /opt/zookeeper/data
    state: directory
    owner: zk
    group: zk


- name: Update Zookeeper Config
  template:
    src: zoo.cfg.j2
    dest: /opt/zookeeper/conf/zoo.cfg
    owner: zk
    group: zk

- name: Open Zookeeper Port 2181
  firewalld:
    port: 2181/tcp
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

- name: Open Zookeeper Port 2888
  firewalld:
    port: 2888/tcp
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

- name: Open Zookeeper Port 3888
  firewalld:
    port: 3888/tcp
    permanent: yes
    immediate: yes
    state: enabled
    zone: public

- name: Create Systemd Service
  template: 
    src: zk.service.j2
    dest: /etc/systemd/system/zk.service
    owner: bin
    group: wheel
    mode: '0644'

- name: Start ZooKeeper
  service:
    name: zk
    state: started
