---
- hosts: brooklin
  become: true
  remote_user: <YOUR REMOTE USER>
  vars:
    SCALA_VERSION: "2.12"
    KAFKA_VERSION: "2.2.0"
    KAFKA_FILENAME: "kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}"
    KAFKA_TGZ: "{{ KAFKA_FILENAME }}.tgz"
    BROOKLIN_VERSION: "1.0.0"
    BROOKLIN_FILENAME: "brooklin-{{ BROOKLIN_VERSION }}"
    BROOKLIN_TGZ: "{{ BROOKLIN_FILENAME }}.tgz"
  tasks:
  - name: Install EPEL 
    yum: 
      name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - name: Run Yum Update
    yum:
      name: '*'
      state: latest
  - name: Install Required Brooklin packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - java-1.8.0-openjdk
      - epel-release
      - jq
  - name: Create Brooklin Install Dirs
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /brooklin
      - /brooklin/kafka
      - /brooklin/brooklin
  - name: Download Kafka
    get_url:
      url: "https://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/{{ KAFKA_TGZ }}"
      dest: /brooklin/kafka
  - name: Extract Kafka
    unarchive:
      remote_src: yes
      src: /brooklin/kafka/{{ KAFKA_TGZ }}
      dest: /brooklin/kafka/
  - name: Download Brooklin
    get_url: 
      url: "https://github.com/linkedin/brooklin/releases/download/{{ BROOKLIN_VERSION }}/{{ BROOKLIN_TGZ }}"
      dest: /brooklin/brooklin
  - name: Extract Brooklin
    unarchive:
      remote_src: yes
      src: /brooklin/brooklin/{{ BROOKLIN_TGZ }}
      dest: /brooklin/brooklin/
